// GENERATED by @edgedb/generate v0.5.6

import * as $ from "../reflection";
import * as _ from "../imports";
import type * as _std from "./std";
export type $UserId = $.ScalarType<"std::number", number>;
const UserId: $.scalarTypeWithConstructor<_std.$number, string> = $.makeType<$.scalarTypeWithConstructor<_std.$number, string>>(_.spec, "f75834ca-a98a-11ef-95de-c1befcc7f5ae", _.syntax.literal);

export type $CourseλShape = $.typeutil.flatten<_std.$Object_8ce8c71ee4fa5f73840c22d7eaa58588λShape & {
  "cid": $.PropertyDesc<_std.$int32, $.Cardinality.One, false, false, false, false>;
  "duration": $.PropertyDesc<_std.$int32, $.Cardinality.One, false, false, false, false>;
  "img": $.PropertyDesc<_std.$str, $.Cardinality.One, false, false, false, false>;
  "price": $.PropertyDesc<_std.$float64, $.Cardinality.One, false, false, false, false>;
  "rating": $.PropertyDesc<_std.$float64, $.Cardinality.One, false, false, false, false>;
  "skills": $.PropertyDesc<_std.$str, $.Cardinality.One, false, false, false, false>;
  "tag": $.PropertyDesc<_std.$str, $.Cardinality.One, false, false, false, false>;
  "title": $.PropertyDesc<_std.$str, $.Cardinality.One, false, false, false, false>;
}>;
type $Course = $.ObjectType<"default::Course", $CourseλShape, null, [
  ..._std.$Object_8ce8c71ee4fa5f73840c22d7eaa58588['__exclusives__'],
]>;
const $Course = $.makeType<$Course>(_.spec, "6c20cc69-a8c9-11ef-b57a-eb670ca72682", _.syntax.literal);

const Course: $.$expr_PathNode<$.TypeSet<$Course, $.Cardinality.Many>, null> = _.syntax.$PathNode($.$toSet($Course, $.Cardinality.Many), null);

export type $UserλShape = $.typeutil.flatten<_std.$Object_8ce8c71ee4fa5f73840c22d7eaa58588λShape & {
  "email": $.PropertyDesc<_std.$str, $.Cardinality.One, false, false, false, false>;
  "fullName": $.PropertyDesc<_std.$str, $.Cardinality.One, false, false, false, false>;
  "password": $.PropertyDesc<_std.$str, $.Cardinality.One, false, false, false, false>;
  "enrolled": $.PropertyDesc<$.ArrayType<_std.$int32>, $.Cardinality.One, false, false, false, true>;
  "uid": $.PropertyDesc<$UserId, $.Cardinality.One, true, false, false, true>;
}>;
type $User = $.ObjectType<"default::User", $UserλShape, null, [
  ..._std.$Object_8ce8c71ee4fa5f73840c22d7eaa58588['__exclusives__'],
  {uid: {__element__: $UserId, __cardinality__: $.Cardinality.One | $.Cardinality.AtMostOne },},
]>;
const $User = $.makeType<$User>(_.spec, "204292e4-a88d-11ef-ad30-d568da35bfd9", _.syntax.literal);

const User: $.$expr_PathNode<$.TypeSet<$User, $.Cardinality.Many>, null> = _.syntax.$PathNode($.$toSet($User, $.Cardinality.Many), null);



export { UserId, $Course, Course, $User, User };

type __defaultExports = {
  "UserId": typeof UserId;
  "Course": typeof Course;
  "User": typeof User
};
const __defaultExports: __defaultExports = {
  "UserId": UserId,
  "Course": Course,
  "User": User
};
export default __defaultExports;
